# permissions to do edit gangs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gang-editor-role
rules:
- apiGroups:
  - batch.wangyun.com
  resources:
  - gangs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.wangyun.com
  resources:
  - gangs/status
  verbs:
  - get
  - patch
  - update
