apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        batch.wangyun.com/gang: gang-sample
      finalizers:
        - batch.wangyun.com/gang
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"